### PR TITLE
Stabilize another test

### PR DESCRIPTION
**Pull request by MenschNestor**
The test execution was non-deterministic due to the executor service with two threads. This was executing the runnables with essentially random order and timing. The runnables are now executed one after the other on a single thread, which still allows to test the caching behaviour.

### CODE REVIEW

**Comment by MenschNestor** [comment]
@howardyuan Thanks for the previous merge. This one fixes a test that failed intermittently, so I did not fix it initially because I could not find the cause at the time.

**Comment by erichhsun** [comment]
@MenschNestor quick question, what method were you using to reproduce the failing tests in question?

**Comment by MenschNestor** [comment]
@erichhsun For this one, I didn't ;-) I've had some experience with using multi-threading in tests.

For the previous ones, the key was finding out that the build VM used by Travis only has 2 cores. This directly impacts the RxJava computation scheduler and the Grizzly web server used in the tests. Once I had found out the system properties I could set to simulate a limited number of cores, the tests were failing consistently.

For example, the property `rx.scheduler.max-computation-threads` allows you to limit the number of threads on the computation scheduler to 2, which mirrors the situation on the build VM.

**Comment by erichhsun** [comment]
@MenschNestor thank you for sharing, that is very helpful.

**Comment by MenschNestor** [comment]
@howardyuan @qiangdavidliu Please merge this PR. If there's any other contact at Netflix that I should be asking instead, please refer me to them.

**Pull request merged**
