### PR TITLE
iss1328: fix

### PR DESCRIPTION
**Pull request by dmgcodevil**
https://github.com/Netflix/Hystrix/issues/1328

cc @mattrjacobs / @VaultB0Y

### CODE REVIEW

**Comment by mattrjacobs** [comment]
Thanks @dmgcodevil !

**Comment by deepzGitHub** [comment]
@mattrjacobs - Can you please which version I should be grabbing to get this fix. Thanks.

**Comment by mattrjacobs** [comment]
I just released v1.5.6, which contains this fix.  Please report back if it resolves your issue

**Comment by deepzGitHub** [comment]
@mattrjacobs - Thanks, grabbed v1.5.6 and tested. Thanks works, Cheers!

**Pull request merged**
