### PR TITLE
set threads to daemon as per #759

### PR DESCRIPTION
**Pull request by cplee**

### CODE REVIEW

**Comment by mattrjacobs** [comment]
Thanks for the contribution, @cplee .  Just to be clear about what this does, this should only change the behavior at JVM shutdown, correct?  In current releases, Hystrix threads need to be explicitly killed and your change would allow the JVM to do the killing.  Did I summarize that properly?

**Comment by cplee** [comment]
@mattrjacobs Yes, the only change in behavior should be at JVM shutdown.  Per the javadoc, _"The Java Virtual Machine exits when the only threads running are all daemon threads."_

**Comment by mattrjacobs** [comment]
I only have experience in an environment where we never attempt graceful shutdown, so we're used to threads stopping abruptly.  I guess the concern here would be things like I/O writes being in an incomplete state and now getting killed without being allowed to come to a natural end.

I also took a closer look and, in practice, we are using a custom concurrency plugin at Netflix in production to set all threads to be daemon threads already - we just never changed this to be the default in open-source Hystrix.

/cc @benjchristensen Any history on this that you can recall?

**Comment by benjchristensen** [comment]
I believe there were other things that prevented a clean shutdown which is why the Hystrix.reset() API was added but I can't remember. 

It won't hurt anything to have the threads be daemons.

**Comment by mattrjacobs** [comment]
@benjchristensen Thanks for the confirmation.  

@cplee Merging now.

**Pull request merged**
