### PR TITLE
Fix for #918

### PR DESCRIPTION
**Pull request by william-tran**

### CODE REVIEW

**Comment by mattrjacobs** [comment]
This is great, thanks @william-tran .

**Comment by william-tran** [comment]
Thanks for blessing the change, even after some of my own testing I wasn't 100% about this. Now we've doubled the capacity!

**Comment by mattrjacobs** [comment]
Can you describe what you have reservations about?  I'm not a JS/front-end developer, so I did a sanity check that the dashboard loads and displays data with your fix, but that's about it.  If you can describe what the tradeoff inherent in your change is, that would be very helpful.

**Comment by william-tran** [comment]
My only reservations were that I'm also not a JS/front-end developer, but asking my peers about it who are and doing my own research, the change seems fundamentally sound.

**Comment by mattrjacobs** [comment]
Fixes #918

**Pull request merged**
