### PR TITLE
Enable Hystrix Dashboard to monitor multiple independent applications

### PR DESCRIPTION
**Pull request by sasrin**
Create a list of hystrix streams to monitor and monitor them independently
using a monitor page.

Backward compatible with existing monitor web url bookmarks.

Implements #906.

### CODE REVIEW

**Comment by sasrin** [comment]
I am not sure why the test cases have failed. [Travis build at the fork](https://travis-ci.org/sasrin/Hystrix) has succeeded with this commit.

**Comment by mattrjacobs** [comment]
Thanks for the PR, @sasrin .  I agree that the failing tests a re unrelated.  I'll take a look at seeing why CI is unhappy with them.

I'll also play with the dashboard in your PR and give feedback there.  If any other dashboard users want to give feedback, that would be very helpful as well

**Comment by sasrin** [comment]
@mattrjacobs  ... sounds good. thank you.

**Comment by mattrjacobs** [comment]
@sasrin My apologies for the delay on reviewing this.  It looks like it works as expected to me.  I can definitely imagine this would be very beneficial to many users - thanks for the contribution!

I pointed at 2 instances that have a large number of commands (~200) and the dashboard performance was fairly slow.  So I don't think this can be used in all cases, but I'm sure it will help certain applications.

There's no reason it can't be used as before (single stream), so my strong inclination is to merge this.  Does anybody object to merging this?

**Comment by sasrin** [comment]
@mattrjacobs Thank you for accepting this pull request.

> I pointed at 2 instances that have a large number of commands (~200) and the dashboard performance was fairly slow. So I don't think this can be used in all cases, but I'm sure it will help certain applications.

Agree with you about the slowness in refreshing the metrics and I did see similar behavior when I  monitored six of our applications(approx. total of 35 endpoints to monitor) with a delay of few milliseconds rather than the default delay of 2 seconds.

**Pull request merged**
