### PR TITLE
#1390 HystrixPlugins.getInstance() returns private instance

### PR DESCRIPTION
**Pull request by sahlex**
changed inner class HystrixPlugins$LazyHolder to public.

### CODE REVIEW

**Comment by mattrjacobs** [comment]
My understanding is that the inner-class `HystrixPlugins$LazyHolder` must be private in order to provide a guarantee that it is not initialized until explicitly asked for via `HystrixPlugins.getInstance()`.  Do I have that right, @agentgt?

If that's correct, then that is in conflict with how OSGi wants to set things up.  We can start looking at other initialization strategies unless someone has a good idea on how to satisfy both goals.

**Comment by agentgt** [comment]
That is correct. I also commented (rambled on and on 😄 ) on #1390.

I took a look at other OSGi friendly libraries that have singletons (ie slf4j) and it appears the consensus is to go the volatile double checked locking route. Originally I was concerned with the volatile but I figure if slf4j is doing it it probably is ok performance wise. It actually is fairly difficult anyway to test for the performance part.

You probably already know but double locking looks like this (copied from wikipedia):

```
class Foo {
    private volatile Helper helper;
    public Helper getHelper() {
        Helper result = helper;
        if (result == null) {
            synchronized(this) {
                result = helper;
                if (result == null) {
                    helper = result = new Helper();
                }
            }
        }
        return result;
    }
}
```

Replace Helper and Foo with HystrixPlugins.

**Comment by sahlex** [comment]
Thanks for investigating! In the meantime I started to set my server up freshly. Out of whatever reasons, the class loading error does not show up any more when using the originally released hystrix-core 1.5.6 artifact.

So the whole thing turned out to be due to some misconfiguration of my environment. 

Sorry for the inconvenience.

Alexander

**Comment by sahlex** [comment]
superseded

**Comment by mattrjacobs** [comment]
Thanks for chiming in @agentgt, I appreciate it.  Looks like we'll leave the init-strategy alone

**Pull request closed without merging**
