### PR TITLE
fix(title-xss): escaping text acquired from parameters to avoid any xss attacks

### PR DESCRIPTION
**Pull request by xscreach**
Use JQuery .text() function to escape title to avoid any XSS attacks.

### CODE REVIEW

**Comment by mattrjacobs** [comment]
Thanks @xscreach

**Comment by xscreach** [comment]
Wow, that was really quick - Thanks @mattrjacobs 

Just a question, when i can expect it to be in some released version?

**Comment by mattrjacobs** [comment]
I'm in the middle of getting a RC together for 1.5.0, so hard to say in that branch.  1.4.x can go out anytime - how urgent would you describe your fix as?

**Comment by xscreach** [comment]
Nothing really urgent - it's minor thing and I've implemented workaround for it in our installation process. 
I just would like to get rid of the workaround as soon as possible so if you'll have time to release 1.4.x it would be great, but it can really wait.
Should i do something to help with getting it into 1.4.x? (create another PR against 1.4.x branche or...?)

**Comment by mattrjacobs** [comment]
Released in 1.4.17

**Comment by xscreach** [comment]
@mattrjacobs - I have to say this, although i was not participating to much opensource projects, but the speed of merging request and getting stuff released/done here is just wonderful.

Thank you very much!

**Comment by mattrjacobs** [comment]
That's great to hear @xscreach.  I'm always happy to have contributions, and especially in areas in which I'm less familiar.  If you see anything else worth fixing/cleaning up in the dashboard, please feel free to create an issue/submit a PR.

**Pull request merged**
