### PR TITLE
Use state classes in CircuitBreaker

### PR DESCRIPTION
**Pull request by mwhipple**
Some concerns I have with the changes in: https://github.com/Netflix/Hystrix/commit/c9241ac1a432a3c4eaef3d83a76bf2ccf73c9342#diff-6c58711cb060a8c1b1435ff1e698bb2d

* The specific responsibilities of `circuitOpened` and the current enum value are unclear in terms of how the logic interacts with them.
* `circuitOpened` and the enum value are interdependent but are updated separately; the lack of internal insurance of consistency seems fragile.
* The system can be left in a half-open state if for some reason the single request allowed does not return to one of the mark[Non]Success methods.

There have been several bugs filed related to these concerns. This PR is my thoughts to address the first two and to make the last one more obvious, I'll add a second commit which aims to avoid being stuck in half-open without relying on any external code to do the right thing.

### CODE REVIEW

**Comment by mwhipple** [comment]
Resolves #1806

**Comment by mwhipple** [comment]
Resolves #1723

**Comment by mwhipple** [comment]
Subsumes #1640

**Comment by gvespucci** [comment]
Hi @mwhipple , I'm not sure to understand why you closed this one. Asking because I maybe found an issue #1723 related. Thanks

**Comment by mwhipple** [comment]
@gvespucci I closed this just because Hystrix seems abandoned in favor of newer alternatives. Last I knew the issues likely still exist but it seemed unlikely that this PR would be merged so I closed it at some point while doing some GitHub housecleaning.

I can reopen if desired. The code here can be packaged into a usable jar. I think a fair amount of the issues were also introduced in the commit linked to above so using a release prior to that commit also avoids the issues.

**Comment by gvespucci** [comment]
Thank you for the explanation @mwhipple ! I'll have a look a that commit as well. 👋

**Pull request closed without merging**
