### PR TITLE
Allow exceptions without HystrixRuntimeException wrapper

### PR DESCRIPTION
**Pull request by tbvh**
Introduce NotWrappedByHystrix to mark Exceptions that should not be wrapped in HystrixRunetimeException.

Partial fix for #1283 .

### CODE REVIEW

**Comment by mattrjacobs** [comment]
Thanks for the PR @tbvh !  This looks like a good change to me.  I'm trying to think through side-effects of this change.

A) Only users who opt into using this interface get a change in behavior - that's a good thing
B) At runtime, the effect of the change is that executions that return any Exception instance which implements `ExceptionNotWrappedByHystrix` gets the raw exception
C) These exceptions manifest as FAILURE in the `FailureType` enum and metrics

For C), would it make sense to have a new event type (UNWRAPPED_FAILURE) that would make it easier to distinguish this scenario?

Any other users in the community have thoughts on this change?

**Comment by Sunshow** [comment]
So will this PR be merged to master?

**Comment by tbvh** [comment]
I just posted https://github.com/Netflix/Hystrix/issues/1283#issuecomment-267159727. 

Just to clarify, I've introduced this as a partial fix, but it completely solves point 1 of issue #1283. In the comment I propose to drop point 2, which make this PR in fact a complete fix.

Makes me all the more curious to the review. :)

**Comment by mattrjacobs** [comment]
A couple thumbs-up from the community and I agree with the change.  I think it's fine not to special-case this for metrics.  A failure of the wrapped work should be a FAILURE as far as metrics are concerned, whether the exception is passed back directly or now.  If anyone disagrees with this, then I think that' fine to have in a follow-on PR.

**Pull request merged**
