### PR TITLE
iss993: added DefaultProperties annotation [ready for review]

### PR DESCRIPTION
**Pull request by dmgcodevil**
fix for https://github.com/Netflix/Hystrix/issues/993

### CODE REVIEW

**Comment by dmgcodevil** [comment]
PR in progress...

**Comment by mattrjacobs** [comment]
Is this ready for review?

**Comment by dmgcodevil** [comment]
Not yet, in progress. Will let you know when it's ready.

**Comment by dmgcodevil** [comment]
@mattrjacobs it's ready for review. BTW is it possible to use java 8 ? I'm still using java 6 for javanica.

**Comment by spencergibb** [comment]
If I recall, 1.x is maintaining JVM 6. If not I'd ask to wait for 2.0 to change that.

**Comment by dmgcodevil** [comment]
It's ok. Will refactor it latter once 2.0 released. If PR is ok you can
merge it.

**Comment by mattrjacobs** [comment]
Yes, let's hold off on Java8 until 2.0

**Comment by mattrjacobs** [comment]
LGTM.  Thanks @dmgcodevil !  I'll close #993.  I'll get master in shape for a 1.5.4 release as well

**Pull request merged**
