### PR TITLE
Fix race condition in HystrixSampleSseServlet for response writes

### PR DESCRIPTION
**Pull request by erichhsun**
Referencing issue: https://github.com/Netflix/Hystrix/issues/1756

### CODE REVIEW

**Comment by henrik242** [comment]
@erichhsun Is there anything you can do to fix the build? It might make it easier to get this PR approved.  I hope to avoid using a self-patched version :)

**Comment by erichhsun** [comment]
@henrik242, not sure. There are intermittent test failures in the
hystrix-core subproject that I can't personally reproduce on my machine.
The changes I made only affected hystrix-contrib. If you do `gradle
:hystrix-core:dependencies`, you'll see that the project has no dependency
on hystrix-contrib, so I doubt it's something my changes introduced. Not
familiar with Travis CI but it could be that resource availability could be
affecting race conditions or test setup in the unit tests?

**Comment by henrik242** [comment]
Maybe try to trigger a rebuild?

**Comment by erichhsun** [comment]
Didn't realize I could do that. I've closed and re-opened this PR to trigger a re-run of the build. It has still failed here:

```
com.netflix.hystrix.HystrixCollapserTest > testRequestVariableLifecycle1 STANDARD_ERROR
    Exception in thread "hystrix-OWNER_ONE-1" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.RuntimeException: Failed executing wrapped Action0
    	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:71)
    	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    	... 5 more
    Caused by: rx.exceptions.OnErrorNotImplementedException: batchResponse was null and we blew
```

I'll see if I get a chance to investigate this further later this week. Can you take a look if you get a chance?

**Comment by henrik242** [comment]
Maybe @mattrjacobs or @benjchristensen can help?  They seem to have been active in this module earlier...

**Comment by spencergibb** [comment]
Neither of them work at Netflix anymore and are not maintainers of this project anymore.

**Comment by erichhsun** [comment]
@qiangdavidliu can we get some help here?

**Comment by MenschNestor** [comment]
BTW, the master builds have been failing for some time now as well, so there's really not much evidence that this change broke the build.

**Comment by henrik242** [comment]
So who is able to merge this? We've been using the patched version in production for awhile, and it fixes our issues..

**Comment by MenschNestor** [comment]
@henrik242 I'm currently having a look at the tests and trying to fix them. Maybe I can get the build more stable, but no promises right now …

**Comment by MenschNestor** [comment]
Quick update: I'm working on #1785 but it's a slog. The reporting from the travis build is … suboptimal.

**Comment by erichhsun** [comment]
Some tests are still failing even after @MenschNestor 's changes, so I think there's other stuff going on here. I'll try to take a look at what's going on tomorrow or by the weekend.

**Comment by MenschNestor** [comment]
@erichhsun Yes, there are more flaky tests unfortunately. I'll have a look – the master build failed as well after my PR was merged.

**Comment by MenschNestor** [comment]
@erichhsun The PR #1786 is aiming to fix the test that was failing your build.

BTW, the stack trace is not the test failure – some of the tests provoke exceptions on purpose. I added output in the last PR at the end of the Travis build log which shows the tests that failed. (You need to view the raw log to find it.)

**Comment by erichhsun** [comment]
Yes, you're right, I believe I copied the wrong stack trace. I needed to grep for `FAILED` instead of ERROR, since ERROR level logs are generated as part of the exceptions thrown on purpose.

This was the correct stack trace:
```
com.netflix.hystrix.UnsubscribedTasksRequestCacheTest > testOneCommandIsUnsubscribed FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.failNotEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:128)
        at org.junit.Assert.assertEquals(Assert.java:472)
        at org.junit.Assert.assertEquals(Assert.java:456)
        at com.netflix.hystrix.UnsubscribedTasksRequestCacheTest.testOneCommandIsUnsubscribed(UnsubscribedTasksRequestCacheTest.java:147)
```

**Comment by erichhsun** [comment]
Build is now passing due to #1786 being merged, thanks to @MenschNestor. @timbozo , can this one be merged?

**Comment by henrik242** [comment]
@drobertduke Hi! Any idea when a new version of hystrix-metrics-event-stream will be released?

**Comment by henrik242** [comment]
Spoke too soon. 1.5.18 is just a re-release of 1.5.11 :(

**Comment by yaofashan** [comment]
When will it be released?

**Comment by henrik242** [comment]
Never, it seems :( I've added this patch on top of 1.5.18 if you'd like to build it yourself: https://github.com/henrik242/Hystrix/tree/finn-1.5.18

**Comment by wangxfholly** [comment]
did it be pushed and released？in 1.5.18

**Comment by henrik242** [comment]
@wangxfholly Nope :(  You'll have to build your own.

**Pull request merged**
