### PR TITLE
Fix a dead link in README.md

### PR DESCRIPTION
**Pull request by nyango**
A link to Apache 2.0 license `[![][license img]][license]` in README.md links to
a dead link https://github.com/Netflix/Hystrix/blob/master/LICENSE-2.0.txt actually, which might not be intended.

### CODE REVIEW

**Comment by spencergibb** [comment]
https://github.com/Netflix/Hystrix/blob/master/LICENSE is a valid url, not sure why you're changing it.

**Comment by nyango** [comment]
A link "License Apache2" does not reach https://github.com/Netflix/Hystrix/blob/master/LICENSE but https://github.com/Netflix/Hystrix/blob/master/LICENSE-2.0.txt.
So, I have tried it.

**Comment by spencergibb** [comment]
That link on the README is broken too.

image

**Comment by nyango** [comment]
Yes, THAT link is broken. This is why I tried to rename `LICENSE → LICENSE-2.0.txt`

**Comment by nyango** [comment]
Yes, THAT link is broken. This is why I tried to rename `LICENSE → LICENSE-2.0.txt`
Try it again at the branch https://github.com/nyango/Hystrix/tree/nyango-patch-1

**Comment by mattrjacobs** [comment]
Thanks @nyango and @spencergibb !

**Pull request merged**
