### PR TITLE
New Feature -- Eureka Integration to Hystrix Dashbaord

### PR DESCRIPTION
**Pull request by diegopacheco**
Hi Guys,

For sake of commodity I load all eureka apps into a select and them the use can just click on the app and it generate the URL for hystryx.stream or turbine.stream.  The rest of the dashboard works as usual and the user still can type if he wants. 

cheers,
Diego Pacheco

### CODE REVIEW

**Comment by mattrjacobs** [comment]
Thanks for the contribution, @diegopacheco.

I tried this out, and it didn't work for me.  I input the domain name of our Eureka VIP, and then clicked on the "Eureka Application" dropdown.  The only element in the list was a greyed-out "Choose Here".  In the browser devtools, I see "net::ERR_CONTENT_DECODING_FAILED" for GET  http://localhost:8080/eureka?url=

Any ideas on what's going wrong on my local installation?

**Comment by diegopacheco** [comment]
hi @mattrjacobs 

For me is working. Which URL are you putting in eureka? Needs to be something that can be queried via REST. Take a look on my print screen. (I'm running on Tomcat) Could you share more details? 

hystrix-dashboard-pr

Cheers,
Diego Pacheco

**Comment by mattrjacobs** [comment]
I just retested this and it worked for me in both Firefox and Chrome.  I have no idea why it didn't work before.  Thanks again for the PR, @diegopacheco , and sincere apologies for the delay

**Comment by diegopacheco** [comment]
Thanks @mattrjacobs

**Pull request merged**
